spring:
  application:
    name: devops
  datasource:
    url: jdbc:postgresql://localhost:5433/devops?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081