spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://${GATEWAY_HOST}:3306/devops?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER} # dbUsername : 환경변수
    password: ${DB_PASSWORD}
  jpa:                                      
    hibernate:
      ddl-auto: create
    show-sql: true
